// Contenu « métier » unique par ville indexée (anti-duplication SEO).
export const cityContentMetier: Record<string, string[]> = {
  "aucamville": [
    "Aux portes nord de Toulouse, Aucamville compte près de 9 600 habitants et appartient à Toulouse Métropole. Située à seulement 8 km du centre toulousain et à une vingtaine de kilomètres de notre atelier de Bessières, cette commune dense mêle pavillons des années 70 et constructions plus récentes. Votre charpentier couvreur à Aucamville connaît bien ce tissu résidentiel et ses contraintes de mitoyenneté.",
    "Sur les toitures aucamvilloises, nous intervenons aussi bien pour reprendre une couverture en tuiles vieillissante que pour traiter une charpente bois fragilisée par l’humidité ou les insectes. Tuiles canal, romanes ou terre cuite du Sud-Ouest : nous remplaçons à l’identique pour respecter l’harmonie des rues et les règles d’urbanisme métropolitaines.",
    "La zinguerie occupe une place importante dans nos chantiers locaux : gouttières en zinc, descentes d’eaux pluviales et solins doivent rester impeccables sur ces parcelles serrées où l’écoulement vers le voisin ne pardonne pas. Nous réalisons également l’isolation de toiture par l’intérieur ou par sarking pour améliorer le confort thermique.",
    "Que vous habitiez vers Fonbeauzard, Launaguet ou en limite de Saint-Alban, nous nous déplaçons rapidement pour un diagnostic gratuit. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente vous accompagne sur l’ensemble de vos projets de couverture à Aucamville.",
  ],
  "aussonne": [
    "Aussonne s’étend dans la plaine de la Garonne, à l’ouest de l’agglomération toulousaine, et rassemble environ 8 000 habitants au sein de Toulouse Métropole. À 13 km de Toulouse et 25 km de Bessières, la commune a connu une forte croissance pavillonnaire autour de son bourg ancien, ce qui génère une grande variété de toitures à entretenir.",
    "Notre savoir-faire de charpentier couvreur à Aussonne couvre la charpente bois sous toutes ses formes : fermettes industrielles des lotissements récents, charpentes traditionnelles des bâtisses anciennes et ossatures bois pour les extensions. Nous diagnostiquons, traitons et renforçons les bois de structure avant toute reprise de couverture.",
    "Côté couverture, nous privilégions les tuiles terre cuite du Sud-Ouest, canal ou romanes, qui donnent aux toits aussonnais leur caractère méridional. La zinguerie en zinc complète le travail : gouttières, chéneaux et noues garantissent une évacuation des eaux durable face aux orages d’été de la plaine.",
    "Proches de Seilh, Gagnac-sur-Garonne et Cornebarrieu, nous proposons aussi l’isolation de combles, la pose de fenêtres de toit et l’installation de pergolas pour profiter du jardin. Faites confiance à un artisan local pour des travaux de toiture soignés et durables à Aussonne.",
  ],
  "balma": [
    "Avec près de 17 800 habitants, Balma est l’une des grandes communes de l’est de Toulouse Métropole, à 5 km à peine du cœur toulousain. Cette proximité immédiate avec la ville-centre, combinée à un patrimoine bâti mêlant maisons de maître, résidences et pavillons, fait de Balma un territoire exigeant pour un charpentier couvreur.",
    "Notre intervention débute toujours par l’examen de la charpente : nous restaurons les charpentes traditionnelles en chêne des demeures anciennes et adaptons les fermettes des constructions plus récentes. Le traitement préventif et curatif des bois contre capricornes et vrillettes fait partie de nos prestations courantes sur le secteur balmanais.",
    "La couverture balmanaise se décline en tuiles canal et romanes ; nous les posons, les démoussons et les remplaçons dans le respect du style local. Notre atelier de zinguerie façonne sur mesure gouttières zinc, descentes et habillages de cheminée pour une finition nette qui résiste aux années.",
    "À une vingtaine de minutes de notre atelier de Bessières, nous desservons aussi Quint-Fonsegrives, Montrabé ou L’Union. Isolation de toiture, fenêtres de velux, pergola bioclimatique : ATB Charpente met son expérience au service de votre toit à Balma.",
  ],
  "beauzelle": [
    "Beauzelle, environ 8 700 habitants, fait figure de commune dynamique de Toulouse Métropole, au nord-ouest de l’agglomération et à 9 km du centre toulousain. Entre le secteur aéronautique de Blagnac voisin et ses quartiers résidentiels, la demande en travaux de toiture y est soutenue et variée.",
    "En tant que charpentier couvreur à Beauzelle, nous traitons d’abord la zinguerie, souvent négligée : une gouttière zinc bouchée ou un solin défaillant suffit à provoquer des infiltrations. Nous reprenons descentes, noues et raccords avant d’intervenir sur la couverture proprement dite.",
    "Sur la couverture, nous restaurons les toits en tuiles terre cuite du Sud-Ouest et remplaçons les éléments cassés ou poreux. La charpente bois n’est jamais oubliée : nous vérifiez son état, renforçons les pièces fatiguées et créons des charpentes neuves pour vos extensions ou abris.",
    "Voisine de Blagnac, Fenouillet et Seilh, Beauzelle bénéficie de notre réactivité depuis Bessières, à 23 km. Isolation thermique de la toiture, pose de fenêtres de toit, construction de pergola : confiez vos projets à un artisan beauzellois de confiance.",
  ],
  "blagnac": [
    "Capitale aéronautique de la métropole toulousaine, Blagnac compte plus de 27 600 habitants et se trouve à 7 km du centre de Toulouse. Cette ville importante, marquée par un habitat dense et un patrimoine résidentiel hétérogène, demande un charpentier couvreur capable de gérer aussi bien des immeubles que des maisons individuelles.",
    "Notre approche blagnacaise commence par la charpente bois : restauration de charpentes traditionnelles, contrôle des fermettes et conception d’ossatures pour vos agrandissements. Nous assurons le traitement complet des bois pour prolonger la vie de votre structure de toit.",
    "La couverture en tuiles, canal ou romanes, reste notre cœur de métier, tout comme la zinguerie zinc qui sécurise l’évacuation des eaux sur les grandes toitures urbaines. Nous posons gouttières, descentes et solins, et intervenons en urgence après tempête.",
    "À 25 km de notre atelier de Bessières, nous rayonnons sur Beauzelle, Cornebarrieu et Aucamville. Isolation de combles, fenêtres de toit et pergolas viennent compléter notre offre : ATB Charpente est votre partenaire toiture à Blagnac.",
  ],
  "bouloc": [
    "Bouloc se situe en pays frontonnais, au nord de Toulouse, et appartient à la CC du Frontonnais avec ses quelque 4 600 habitants. À 21 km de Toulouse mais seulement 15 km de notre atelier de Bessières, ce gros bourg viticole conjugue maisons de caractère et lotissements récents, un terrain de jeu idéal pour un charpentier couvreur de proximité.",
    "Sur ce secteur de coteaux, la charpente traditionnelle est encore très présente : nous restaurons les fermes et pannes en bois massif des anciennes bâtisses agricoles, tout en sachant intervenir sur les fermettes des constructions modernes. Le traitement des bois contre l’humidité et les insectes est systématiquement proposé.",
    "Les toitures bouloçaises en tuiles canal et romanes profitent de notre expertise en pose, réfection et démoussage. La zinguerie zinc, gouttières et descentes comprises, complète chaque chantier pour une étanchéité durable face aux pluies du nord toulousain.",
    "Tout proches de Villaudric, Cépet et Castelnau-d’Estrétefonds, nous proposons également l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. Choisissez un artisan voisin et réactif pour vos travaux de couverture à Bouloc.",
  ],
  "bressols": [
    "Bressols se trouve dans le Tarn-et-Garonne, aux abords de Montauban, et fait partie de la CA Grand Montauban avec environ 4 000 habitants. Plus éloignée de Toulouse (40 km), la commune reste à 29 km de notre atelier de Bessières, ce qui nous permet d’y intervenir régulièrement en tant que charpentier couvreur.",
    "Le bâti bressolais, entre fermes de plaine et pavillons, appelle des compétences en charpente bois variées : nous reprenons les charpentes traditionnelles des corps de ferme et adaptons les fermettes des maisons récentes. Notre diagnostic structure est toujours le point de départ.",
    "Côté toiture, nous travaillons les tuiles terre cuite du Sud-Ouest, canal en tête, et soignons la zinguerie zinc indispensable dans cette plaine sujette aux fortes pluies : gouttières, chéneaux et descentes sont posés dans les règles de l’art.",
    "Voisine de Labastide-Saint-Pierre et Corbarieu, Bressols bénéficie aussi de nos prestations d’isolation de toiture, de pose de fenêtres de toit et de pergolas. ATB Charpente met son sérieux d’artisan au service de votre couverture à Bressols.",
  ],
  "bruguieres": [
    "Bruguières, environ 6 200 habitants, occupe une position stratégique au nord de Toulouse Métropole, à 14 km du centre toulousain et 17 km de Bessières. Traversée par d’importants axes routiers, la commune mêle zones d’activités et quartiers pavillonnaires, offrant à votre charpentier couvreur des chantiers très divers.",
    "Nous commençons souvent par sécuriser la couverture : remplacement de tuiles canal ou romanes cassées, réfection complète de toiture vieillissante et démoussage préventif. Sur les toits récents en terre cuite du Sud-Ouest, nous veillons à conserver l’unité esthétique du quartier.",
    "La charpente bois fait l’objet d’un soin particulier, qu’il s’agisse de restaurer une charpente traditionnelle ou de renforcer des fermettes affaissées. La zinguerie zinc, gouttières et descentes, garantit ensuite une évacuation des eaux sans faille.",
    "Proches de Gratentour, Lespinasse et Saint-Alban, nous complétons notre offre par l’isolation de toiture, la pose de fenêtres de toit et l’installation de pergolas. Pour des travaux soignés et durables, faites appel à un artisan local à Bruguières.",
  ],
  "buzet-sur-tarn": [
    "Buzet-sur-Tarn borde la rivière Tarn et compte près de 3 000 habitants au sein de la CC Val’Aïgo. C’est l’une des communes les plus proches de notre atelier : 3 km seulement nous séparent, contre 23 km de Toulouse. Autant dire que votre charpentier couvreur à Buzet-sur-Tarn est pratiquement votre voisin.",
    "Cette proximité nous permet d’intervenir très rapidement sur les charpentes bois locales : restauration de charpentes traditionnelles des fermes au bord du Tarn, contrôle des fermettes et création d’ossatures bois pour vos projets. Le traitement curatif des bois est une de nos spécialités sur ce secteur humide de bord de rivière.",
    "Les toitures buzétoises en tuiles canal demandent une vigilance accrue face aux crues et aux pluies : nous soignons particulièrement la zinguerie zinc, gouttières, noues et descentes, pour évacuer efficacement les eaux pluviales. Réfection de couverture et démoussage complètent nos prestations.",
    "À deux pas de Mézens, Paulhac et Montastruc-la-Conseillère, nous proposons aussi isolation de toiture, fenêtres de toit et pergolas. Profitez de la réactivité d’un artisan installé à côté de chez vous pour tous vos travaux de toiture à Buzet-sur-Tarn.",
  ],
  "castelginest": [
    "Castelginest, plus de 11 200 habitants, est une commune résidentielle importante du nord de Toulouse Métropole, à 10 km du centre toulousain. Son développement pavillonnaire continu en fait un secteur où les besoins en couverture et charpente ne faiblissent pas, et où votre charpentier couvreur intervient toute l’année.",
    "Sur les toits castelginestois, nous traitons la couverture en tuiles terre cuite du Sud-Ouest avec un soin particulier : réfection, remplacement à l’identique et démoussage. Les nombreuses fermettes des lotissements récents font l’objet d’un contrôle régulier de notre part.",
    "La charpente traditionnelle des bâtisses plus anciennes est restaurée dans les règles, et notre atelier de zinguerie façonne gouttières zinc, descentes et solins sur mesure. L’isolation de toiture, par l’intérieur ou en sarking, améliore sensiblement le confort de votre habitation.",
    "Limitrophe de Saint-Alban, Fonbeauzard et Pechbonnieu, Castelginest se trouve à 17 km de notre atelier de Bessières. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente vous accompagne durablement à Castelginest.",
  ],
  "castelmaurou": [
    "Castelmaurou, environ 4 500 habitants, appartient à la CC des Coteaux Bellevue, sur les hauteurs au nord-est de Toulouse. À 11 km de la ville-centre et 14 km de notre atelier de Bessières, ce village des coteaux offre de belles maisons sur des terrains parfois pentus, ce qui complexifie le travail du charpentier couvreur.",
    "Le relief des coteaux castelmaurens impose une attention particulière à la charpente bois : nous renforçons les structures soumises au vent et restaurons les charpentes traditionnelles des maisons de caractère. Les fermettes des constructions récentes sont contrôlées et consolidées si besoin.",
    "La zinguerie prend ici tout son sens : sur des toits en pente, gouttières zinc, noues et descentes doivent canaliser des volumes d’eau importants. Nous posons une couverture en tuiles canal et romanes parfaitement étanche et soignons chaque raccord.",
    "Voisins de Lapeyrouse-Fossat, Rouffiac-Tolosan et Saint-Jean, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas adaptées aux jardins en pente. Faites confiance à un artisan local pour votre toiture à Castelmaurou.",
  ],
  "castelnau-d-estretefonds": [
    "Castelnau-d’Estrétefonds, plus de 7 000 habitants, se situe au nord de la Haute-Garonne dans la CC du Frontonnais, le long de l’axe Toulouse-Montauban. À 23 km de Toulouse et 20 km de Bessières, cette commune en pleine expansion logistique et résidentielle sollicite régulièrement votre charpentier couvreur.",
    "Entre le château historique et les lotissements neufs, le bâti castelnaurien est contrasté. Nous restaurons les charpentes traditionnelles des demeures anciennes et intervenons sur les fermettes des maisons modernes, avec un traitement systématique des bois contre les nuisibles.",
    "La couverture en tuiles canal et romanes, typique du Sud-Ouest, est notre domaine : pose, réfection et démoussage. La zinguerie zinc, gouttières et descentes, complète l’ouvrage pour une évacuation des eaux fiable face aux pluies du nord toulousain.",
    "Proches d’Ondes, Pompignan et Bouloc, nous réalisons également l’isolation de toiture, la pose de fenêtres de toit et l’installation de pergolas. ATB Charpente, artisan de proximité, soigne chaque détail de votre couverture à Castelnau-d’Estrétefonds.",
  ],
  "cornebarrieu": [
    "Cornebarrieu, près de 9 000 habitants, se développe à l’ouest de Toulouse Métropole, à 11 km du centre toulousain, à proximité immédiate du pôle aéronautique. Cette croissance résidentielle, avec ses écoquartiers et son bourg ancien, offre à votre charpentier couvreur un large éventail de toitures à entretenir.",
    "Sur les constructions récentes de Cornebarrieu, l’isolation de toiture est souvent une priorité : nous intervenons par l’intérieur ou par sarking pour optimiser le confort thermique et les performances énergétiques. Les fenêtres de toit que nous posons apportent lumière et ventilation aux combles aménagés.",
    "La couverture en tuiles terre cuite du Sud-Ouest fait l’objet de nos réfections et démoussages, tandis que la charpente bois, traditionnelle ou en fermettes, est diagnostiquée et renforcée. La zinguerie zinc assure gouttières et descentes durables.",
    "Mitoyenne d’Aussonne, Blagnac et Beauzelle, Cornebarrieu se trouve à 28 km de notre atelier de Bessières. Création de pergola, charpente d’extension, entretien de toiture : ATB Charpente vous accompagne sur tous vos projets à Cornebarrieu.",
  ],
  "coufouleux": [
    "Coufouleux s’étend dans le Tarn, sur la rive du Tarn face à Rabastens, et compte environ 3 000 habitants au sein de la CA Gaillac-Graulhet. À 32 km de Toulouse mais seulement 11 km de notre atelier de Bessières, cette commune viticole reste un terrain d’intervention privilégié pour votre charpentier couvreur.",
    "Le vignoble gaillacois a laissé à Coufouleux un patrimoine de chais et de maisons vigneronnes aux charpentes traditionnelles remarquables. Nous les restaurons avec respect, en conservant les bois sains et en remplaçant les pièces atteintes, après un traitement adapté.",
    "Les toitures coufoulésiennes en tuiles canal réclament une zinguerie zinc soignée : gouttières, descentes et solins protègent ces bâtisses des pluies du Tarn. Nous assurons réfection de couverture, remplacement de tuiles et démoussage en hauteur.",
    "À proximité de Rabastens, Giroussens et Saint-Sulpice-la-Pointe, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. Comptez sur un artisan voisin et disponible pour vos travaux de toiture à Coufouleux.",
  ],
  "daux": [
    "Daux, environ 2 600 habitants, est une commune de la CC des Hauts-Tolosans, au nord-ouest de Toulouse, à 17 km de la ville-centre et 30 km de notre atelier de Bessières. Ce bourg paisible, encore marqué par son caractère rural, voit fleurir de nouvelles constructions qui élargissent nos chantiers de charpentier couvreur.",
    "Ici, la charpente traditionnelle reste fréquente : nous restaurons fermes, pannes et chevrons des maisons anciennes, et nous contrôlons les fermettes des pavillons récents. L’ossature bois est aussi une solution que nous proposons pour vos extensions et abris de jardin.",
    "La couverture en tuiles canal et romanes, emblématique du Sud-Ouest, est posée et rénovée par nos soins. La zinguerie zinc, gouttières et descentes, garantit l’évacuation des eaux, et l’isolation de toiture améliore nettement le confort des combles.",
    "Voisins de Merville, Aussonne et Cornebarrieu, nous installons aussi fenêtres de toit et pergolas. ATB Charpente, artisan attentif et local, prend soin de votre couverture à Daux comme s’il s’agissait de la sienne.",
  ],
  "dremil-lafage": [
    "Drémil-Lafage, environ 2 600 habitants, se niche sur les coteaux du Lauragais au sein de Toulouse Métropole, à 13 km de Toulouse et 23 km de Bessières. Ce village résidentiel, entouré de campagne, séduit par ses maisons individuelles sur de grands terrains, un cadre que votre charpentier couvreur connaît parfaitement.",
    "Sur ces coteaux exposés, la couverture est mise à rude épreuve : nous remplaçons les tuiles canal et romanes endommagées par le vent et la grêle, et nous réfectionnons les toitures vieillissantes en respectant le style local. Le démoussage régulier prolonge la durée de vie des tuiles.",
    "La charpente bois, traditionnelle dans les bâtisses anciennes ou en fermettes dans les constructions récentes, fait l’objet de notre diagnostic et de nos renforts. La zinguerie zinc, gouttières et descentes, et l’isolation de toiture complètent nos interventions.",
    "Proches d’Aigrefeuille, Flourens et Mons, nous posons aussi des fenêtres de toit et créons des pergolas pour profiter des belles vues du Lauragais. Faites appel à un artisan local et soigneux pour votre toiture à Drémil-Lafage.",
  ],
  "fenouillet": [
    "Fenouillet, près de 5 800 habitants, s’inscrit au nord de Toulouse Métropole, à 10 km du centre toulousain et 21 km de notre atelier de Bessières. Entre Garonne et coteaux, cette commune mêle habitat pavillonnaire dense et zones commerciales, offrant à votre charpentier couvreur des toitures de toutes natures.",
    "Notre priorité fenouillétaine est souvent la zinguerie : sur des parcelles serrées, gouttières zinc, descentes et solins doivent être irréprochables pour éviter les infiltrations chez le voisin. Nous reprenons aussi les noues et les habillages de cheminée.",
    "La couverture en tuiles terre cuite du Sud-Ouest est notre cœur de métier : réfection, remplacement à l’identique et démoussage. La charpente bois, qu’elle soit traditionnelle ou en fermettes, est contrôlée et renforcée avant tout travail de toiture.",
    "Limitrophe de Saint-Alban, Beauzelle et Seilh, Fenouillet bénéficie de notre réactivité. Isolation de toiture, fenêtres de toit, pergola : ATB Charpente met son expérience d’artisan au service de votre couverture à Fenouillet.",
  ],
  "fonbeauzard": [
    "Fonbeauzard est l’une des plus petites communes de Toulouse Métropole par sa superficie, avec environ 3 200 habitants, à 8 km seulement du centre toulousain. Cette densité urbaine, faite de pavillons mitoyens et de petits collectifs, demande un charpentier couvreur rigoureux et soigneux.",
    "Sur ces toitures resserrées, la zinguerie est déterminante : nous façonnons et posons gouttières zinc, descentes et solins pour une évacuation des eaux parfaite, condition essentielle dans un habitat dense. Les raccords et habillages sont réalisés avec une grande précision.",
    "La couverture en tuiles canal et romanes est réfectionnée, remplacée et démoussée dans le respect de l’unité des rues. La charpente bois, souvent en fermettes, est diagnostiquée et consolidée, et nous proposons l’isolation de toiture pour gagner en confort.",
    "Entourée d’Aucamville, Castelginest et Launaguet, Fonbeauzard se trouve à 19 km de notre atelier de Bessières. Pose de fenêtres de toit, création de pergola, entretien annuel : confiez votre toiture à un artisan local de confiance à Fonbeauzard.",
  ],
  "fronton": [
    "Fronton, capitale du vignoble du même nom, compte près de 6 700 habitants et structure la CC du Frontonnais, au nord de la Haute-Garonne. À 28 km de Toulouse et 20 km de notre atelier de Bessières, ce bourg viticole conjugue domaines, maisons de maître et lotissements, un patrimoine riche pour votre charpentier couvreur.",
    "Les chais et demeures frontonnaises recèlent de magnifiques charpentes traditionnelles en bois massif que nous restaurons avec passion : reprise des fermes, des pannes et des chevrons, traitement curatif et remplacement à l’identique des pièces atteintes.",
    "La couverture en tuiles canal, typique du Frontonnais, est posée, rénovée et démoussée par nos soins, tandis que la zinguerie zinc, gouttières et descentes, sécurise l’évacuation des eaux. Nous intervenons aussi en urgence après les épisodes orageux qui touchent les coteaux.",
    "Proches de Villaudric, Campsas et Pompignan, nous réalisons l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, artisan ancré dans le terroir frontonnais, soigne votre couverture à Fronton.",
  ],
  "gagnac-sur-garonne": [
    "Gagnac-sur-Garonne, environ 3 200 habitants, longe la Garonne au nord-ouest de Toulouse Métropole, à 13 km du centre toulousain et 22 km de Bessières. Cette commune de bord de fleuve, à l’habitat à taille humaine, présente des toitures que votre charpentier couvreur entretient au fil des saisons.",
    "La proximité de la Garonne rend la zinguerie essentielle : nous portons une attention particulière aux gouttières zinc, noues et descentes pour évacuer efficacement les eaux pluviales et limiter les risques d’humidité. Solins et raccords sont posés avec soin.",
    "La couverture en tuiles canal et romanes du Sud-Ouest fait l’objet de nos réfections, remplacements et démoussages. La charpente bois, traditionnelle ou en fermettes, est diagnostiquée et renforcée, et l’isolation de toiture vient améliorer le confort thermique.",
    "Voisins de Seilh, Lespinasse et Fenouillet, nous installons aussi fenêtres de toit et pergolas. Faites confiance à ATB Charpente, artisan local et réactif, pour tous vos travaux de toiture à Gagnac-sur-Garonne.",
  ],
  "gaillac": [
    "Gaillac, plus de 16 100 habitants, est une ville emblématique du Tarn et le cœur de la CA Gaillac-Graulhet, célèbre pour son vignoble millénaire. C’est la plus éloignée de Toulouse parmi nos communes (49 km), mais elle ne se trouve qu’à 26 km de notre atelier de Bessières, ce qui en fait un secteur d’intervention privilégié pour votre charpentier couvreur.",
    "Le riche patrimoine gaillacois, abbaye, hôtels particuliers et maisons vigneronnes, recèle des charpentes traditionnelles exceptionnelles. Nous les restaurons avec un grand respect du bâti ancien : reprise des fermes, traitement des bois et remplacement à l’identique des éléments dégradés.",
    "Sur les toitures gaillacoises en tuiles canal, nous assurons réfection, démoussage et remplacement, dans le souci de préserver le cachet de la cité. La zinguerie zinc, gouttières, chéneaux et descentes, est façonnée sur mesure pour les bâtiments anciens comme récents.",
    "À proximité de Lisle-sur-Tarn, Brens et Montans, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente met son expertise d’artisan au service de votre couverture à Gaillac.",
  ],
  "gragnague": [
    "Gragnague, environ 2 550 habitants, appartient à la CC des Coteaux du Girou, à l’est de Toulouse. Située à 14 km de la ville-centre et seulement 13 km de notre atelier de Bessières, cette commune des coteaux, à l’habitat dispersé, est tout proche de chez nous, ce qui garantit la réactivité de votre charpentier couvreur.",
    "Sur les coteaux gragnaguais, la charpente bois est souvent traditionnelle : nous restaurons les charpentes des fermes et maisons anciennes, et nous contrôlons les fermettes des constructions récentes. Le traitement préventif des bois prévient capricornes et vrillettes.",
    "Les toitures locales en tuiles canal et romanes sont réfectionnées, remplacées et démoussées par nos soins. La zinguerie zinc, gouttières, noues et descentes, sécurise l’évacuation des eaux sur ces terrains parfois pentus, et l’isolation de toiture améliore le confort.",
    "Proches de Montastruc-la-Conseillère, Garidech et Saint-Jean-Lherm, nous posons aussi des fenêtres de toit et créons des pergolas. Pour un travail soigné par un artisan voisin, choisissez ATB Charpente à Gragnague.",
  ],
  "gratentour": [
    "Gratentour, près de 4 900 habitants, est une commune résidentielle du nord de Toulouse Métropole, à 13 km du centre toulousain et 16 km de notre atelier de Bessières. Son cadre verdoyant et son habitat majoritairement pavillonnaire offrent à votre charpentier couvreur des chantiers réguliers et variés.",
    "Sur les pavillons gratentourois, nous traitons la couverture en tuiles terre cuite du Sud-Ouest : remplacement de tuiles cassées, réfection de toiture et démoussage préventif. Les fermettes des lotissements récents sont contrôlées et renforcées au besoin.",
    "La charpente traditionnelle des maisons plus anciennes est restaurée dans les règles, et la zinguerie zinc, gouttières et descentes, garantit une évacuation des eaux durable. L’isolation de toiture, par l’intérieur ou en sarking, optimise vos consommations énergétiques.",
    "Mitoyenne de Bruguières, Pechbonnieu et Castelginest, Gratentour bénéficie de notre proximité. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente vous accompagne durablement à Gratentour.",
  ],
  "grenade": [
    "Grenade, plus de 9 000 habitants, est une bastide historique de la CC des Hauts-Tolosans, au nord-ouest de Toulouse, à 23 km de la ville-centre et 26 km de Bessières. Sa halle médiévale et ses rues à arcades témoignent d’un patrimoine que votre charpentier couvreur a à cœur de préserver.",
    "Le bâti ancien grenadain abrite de superbes charpentes traditionnelles, à commencer par celle de la halle. Nous restaurons ces ouvrages de bois avec rigueur, en reprenant fermes et pannes, en traitant les bois et en remplaçant à l’identique les pièces fatiguées.",
    "La couverture en tuiles canal, typique des bastides du Sud-Ouest, est posée, rénovée et démoussée par nos soins, dans le respect des règles d’urbanisme de la cité. La zinguerie zinc, gouttières et descentes, complète l’ouvrage avec discrétion.",
    "Proches d’Ondes, Merville et Saint-Rustice, nous réalisons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, respectueux du patrimoine, prend soin de votre couverture à Grenade.",
  ],
  "grisolles": [
    "Grisolles, plus de 4 200 habitants, est une commune du Tarn-et-Garonne rattachée à la CC Grand Sud Tarn-et-Garonne, le long de l’axe Toulouse-Montauban. À 27 km de Toulouse et 25 km de notre atelier de Bessières, ce bourg actif, traversé par le canal, mobilise régulièrement votre charpentier couvreur.",
    "Le bâti grisollais, entre maisons anciennes et constructions récentes, appelle des compétences variées en charpente bois : restauration des charpentes traditionnelles et contrôle des fermettes. Le traitement des bois contre l’humidité et les insectes est toujours proposé.",
    "Côté couverture, nous travaillons les tuiles canal du Sud-Ouest et soignons la zinguerie zinc, gouttières et descentes, indispensable dans cette plaine soumise aux pluies. Réfection de toiture et démoussage prolongent la vie de vos couvertures.",
    "Voisine de Pompignan, Canals et Castelnau-d’Estrétefonds, Grisolles profite aussi de nos prestations d’isolation de toiture, de pose de fenêtres de toit et de pergolas. ATB Charpente met son sérieux d’artisan au service de votre toit à Grisolles.",
  ],
  "l-union": [
    "L’Union, plus de 12 600 habitants, est une commune importante du nord-est de Toulouse Métropole, à 6 km à peine du centre toulousain. Cette ville résidentielle prisée, à l’habitat soigné et souvent haut de gamme, attend de son charpentier couvreur un travail à la hauteur de ses exigences.",
    "Sur les belles demeures unionaises, nous restaurons les charpentes traditionnelles en chêne et contrôlons les fermettes des constructions récentes. Le traitement préventif et curatif des bois protège durablement vos structures de toit.",
    "La couverture en tuiles canal et romanes est réfectionnée et entretenue avec soin, tandis que notre atelier de zinguerie façonne sur mesure gouttières zinc, descentes et habillages décoratifs. L’isolation de toiture vient parfaire le confort de votre habitation.",
    "À 19 km de notre atelier de Bessières et voisine de Saint-Jean, Launaguet et Balma, L’Union bénéficie de notre savoir-faire. Pose de fenêtres de toit, pergola bioclimatique, entretien : ATB Charpente est votre partenaire toiture à L’Union.",
  ],
  "labastide-saint-pierre": [
    "Labastide-Saint-Pierre, près de 3 750 habitants, est une commune du Tarn-et-Garonne au sein de la CC Grand Sud Tarn-et-Garonne, dans la plaine au sud de Montauban. À 36 km de Toulouse et 25 km de notre atelier de Bessières, ce bourg en développement fait régulièrement appel à votre charpentier couvreur.",
    "Le bâti labastidien mêle anciennes fermes de plaine et lotissements neufs. Nous restaurons les charpentes traditionnelles des corps de ferme et intervenons sur les fermettes des maisons récentes, avec un traitement systématique des bois.",
    "La couverture en tuiles canal du Sud-Ouest fait l’objet de nos réfections et démoussages, et la zinguerie zinc, gouttières et descentes, est posée avec soin pour évacuer les pluies de la plaine tarn-et-garonnaise. Nous intervenons aussi en urgence après tempête.",
    "Proches de Corbarieu, Bressols et Campsas, nous proposons l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, artisan disponible et minutieux, soigne votre couverture à Labastide-Saint-Pierre.",
  ],
  "labege": [
    "Labège, près de 4 400 habitants, est connue pour son important pôle économique et technologique, au sud-est de Toulouse, au sein de la CA du Sicoval. À 10 km du centre toulousain mais 29 km de notre atelier de Bessières, cette commune dynamique présente un bâti mêlant tertiaire et résidentiel que votre charpentier couvreur maîtrise.",
    "Sur les maisons labégeoises, l’isolation de toiture est fréquemment demandée pour répondre aux enjeux énergétiques : nous intervenons par l’intérieur ou en sarking, et posons des fenêtres de toit pour éclairer naturellement vos combles aménagés.",
    "Côté couverture, nous reprenons les toits en tuiles canal et romanes du Sud-Ouest, du simple remplacement de tuiles à la réfection complète, démoussage inclus. La charpente bois, qu’elle soit traditionnelle ou montée en fermettes, est systématiquement contrôlée, et notre zinguerie zinc sécurise gouttières, descentes et solins.",
    "Voisine de Saint-Orens-de-Gameville, Ramonville-Saint-Agne et Auzielle, Labège bénéficie de notre savoir-faire complet. Création de pergola, charpente d’extension, entretien de toiture : ATB Charpente vous accompagne à Labège.",
  ],
  "lapeyrouse-fossat": [
    "Lapeyrouse-Fossat, environ 3 000 habitants, s’étire sur les coteaux du nord-est toulousain au sein de la CC des Coteaux du Girou. À 12 km de Toulouse et seulement 13 km de notre atelier de Bessières, ce village vallonné, proche de chez nous, garantit la réactivité de votre charpentier couvreur.",
    "Le relief des coteaux impose un soin particulier à la charpente bois : nous renforçons les structures exposées au vent et restaurons les charpentes traditionnelles des maisons de caractère. Les fermettes des constructions récentes sont contrôlées et consolidées.",
    "La couverture en tuiles canal et romanes, sur des toits souvent pentus, est posée et réfectionnée avec rigueur. La zinguerie zinc prend ici toute son importance : gouttières, noues et descentes canalisent des volumes d’eau conséquents lors des orages.",
    "Proches de Montberon, Castelmaurou et Saint-Loup-Cammas, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. Pour un travail soigné par un artisan voisin, choisissez ATB Charpente à Lapeyrouse-Fossat.",
  ],
  "launaguet": [
    "Launaguet, plus de 9 100 habitants, est une commune résidentielle du nord de Toulouse Métropole, à 7 km du centre toulousain et 19 km de notre atelier de Bessières. Entre château, parcs et quartiers pavillonnaires, cette ville en croissance offre à votre charpentier couvreur une grande diversité de toitures.",
    "Nous débutons souvent par la couverture : remplacement de tuiles canal ou romanes endommagées, réfection complète de toiture vieillissante et démoussage préventif. Sur les toits récents en terre cuite du Sud-Ouest, nous respectons l’harmonie des lotissements.",
    "La charpente bois, traditionnelle dans les bâtisses anciennes ou en fermettes dans les constructions modernes, est diagnostiquée et renforcée. La zinguerie zinc, gouttières et descentes, et l’isolation de toiture complètent chacune de nos interventions.",
    "Limitrophe de Fonbeauzard, Saint-Geniès-Bellevue et L’Union, Launaguet bénéficie de notre proximité. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente prend soin de votre couverture à Launaguet.",
  ],
  "lavaur": [
    "Lavaur, près de 11 000 habitants, est une ville historique du Tarn et le siège de la CC Tarn-Agout, dominée par sa cathédrale Saint-Alain. À 31 km de Toulouse mais seulement 21 km de notre atelier de Bessières, cette cité d’art et d’histoire mobilise pleinement le savoir-faire de votre charpentier couvreur.",
    "Le patrimoine vauréen, riche de demeures anciennes et d’édifices remarquables, recèle de superbes charpentes traditionnelles. Nous les restaurons avec rigueur : reprise des fermes et pannes, traitement curatif des bois et remplacement à l’identique des éléments dégradés.",
    "Les toitures vauréennes en tuiles canal sont réfectionnées, remplacées et démoussées dans le respect du caractère de la ville. La zinguerie zinc, gouttières, chéneaux et descentes, est façonnée sur mesure pour les bâtiments anciens comme contemporains.",
    "Proches d’Ambres, Labastide-Saint-Georges et Marzens, nous réalisons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente met son expertise au service de votre couverture à Lavaur.",
  ],
  "lespinasse": [
    "Lespinasse, environ 3 250 habitants, occupe une position de carrefour au nord de Toulouse Métropole, entre Garonne et grands axes, à 14 km du centre toulousain et 20 km de Bessières. Cette commune compacte, à l’habitat pavillonnaire, fait régulièrement appel à votre charpentier couvreur.",
    "Sur les toits lespinassois, la zinguerie est souvent prioritaire : nous façonnons et posons gouttières zinc, descentes et solins pour une évacuation des eaux irréprochable, essentielle à proximité de la Garonne. Les noues et raccords sont réalisés avec précision.",
    "La couverture en tuiles canal et romanes du Sud-Ouest est réfectionnée, remplacée et démoussée par nos soins. La charpente bois, traditionnelle ou en fermettes, est diagnostiquée et renforcée, et l’isolation de toiture améliore le confort thermique.",
    "Voisins de Gagnac-sur-Garonne, Bruguières et Saint-Jory, nous installons aussi fenêtres de toit et pergolas. Faites confiance à ATB Charpente, artisan local et réactif, pour tous vos travaux de toiture à Lespinasse.",
  ],
  "lisle-sur-tarn": [
    "Lisle-sur-Tarn, près de 4 950 habitants, est une bastide du Tarn rattachée à la CA Gaillac-Graulhet, réputée pour sa place à couverts, l’une des plus grandes du Sud-Ouest. À 42 km de Toulouse mais seulement 17 km de notre atelier de Bessières, cette cité viticole sollicite volontiers votre charpentier couvreur.",
    "Le bâti lislois, fait de maisons à colombages et de demeures vigneronnes, abrite de remarquables charpentes traditionnelles. Nous les restaurons dans le respect du patrimoine : reprise des bois de structure, traitement curatif et remplacement à l’identique.",
    "Les toitures de la bastide, en tuiles canal, sont réfectionnées, remplacées et démoussées avec soin. La zinguerie zinc, gouttières et descentes, façonnée sur mesure, protège ces bâtisses anciennes des pluies du Tarn tout en respectant leur cachet.",
    "Proches de Rabastens, Loupiac et Gaillac, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, attaché au patrimoine local, soigne votre couverture à Lisle-sur-Tarn.",
  ],
  "merville": [
    "Merville, près de 6 800 habitants, appartient à la CC des Hauts-Tolosans, au nord-ouest de Toulouse, et abrite l’un des plus longs châteaux à pans de bois de France. À 18 km de la ville-centre et 26 km de Bessières, cette commune au beau patrimoine offre à votre charpentier couvreur des chantiers stimulants.",
    "Le château et les demeures mervilloises témoignent d’une tradition de charpente bois exceptionnelle. Nous restaurons fermes, pannes et chevrons des bâtisses anciennes, et nous contrôlons les fermettes des constructions récentes, avec un traitement systématique des bois.",
    "La couverture en tuiles canal et romanes du Sud-Ouest est posée, rénovée et démoussée par nos soins. La zinguerie zinc, gouttières et descentes, assure une évacuation des eaux durable, et l’isolation de toiture améliore sensiblement le confort des combles.",
    "Voisins de Daux, Aussonne et Grenade, nous installons aussi fenêtres de toit et pergolas. ATB Charpente, artisan attentif au patrimoine, prend soin de votre couverture à Merville.",
  ],
  "montastruc-la-conseillere": [
    "Montastruc-la-Conseillère, environ 3 700 habitants, est un chef-lieu de la CC des Coteaux du Girou, à l’est de Toulouse. Située à 17 km de la ville-centre et seulement 9 km de notre atelier de Bessières, cette commune toute proche garantit une réactivité maximale de votre charpentier couvreur.",
    "Notre proximité immédiate nous permet d’intervenir vite sur les charpentes bois montastrucoises : restauration des charpentes traditionnelles des maisons de caractère et contrôle des fermettes des lotissements récents. Le traitement curatif des bois est l’une de nos spécialités.",
    "Les toitures locales en tuiles canal et romanes sont réfectionnées, remplacées et démoussées par nos soins. La zinguerie zinc, gouttières, noues et descentes, sécurise l’évacuation des eaux, et l’isolation de toiture optimise le confort de votre habitation.",
    "Voisins de Gémil, Garidech et Gragnague, nous posons aussi des fenêtres de toit et créons des pergolas. Pour un service rapide et soigné par un artisan installé tout près, choisissez ATB Charpente à Montastruc-la-Conseillère.",
  ],
  "montberon": [
    "Montberon, environ 3 150 habitants, se situe sur les coteaux Bellevue au nord de Toulouse, au sein de la CC des Coteaux Bellevue. À 13 km de la ville-centre et seulement 13 km de notre atelier de Bessières, ce village résidentiel vallonné est tout proche de chez nous, ce qui assure la réactivité de votre charpentier couvreur.",
    "Sur les coteaux montberonnais, la charpente bois mérite une attention particulière face au vent : nous renforçons les structures et restaurons les charpentes traditionnelles, tout en contrôlant les fermettes des constructions récentes.",
    "La couverture en tuiles canal et romanes, sur des toits parfois pentus, est posée et réfectionnée avec rigueur. La zinguerie zinc, gouttières, noues et descentes, canalise efficacement les eaux pluviales, et l’isolation de toiture améliore le confort.",
    "Proches de Lapeyrouse-Fossat, Saint-Loup-Cammas et Pechbonnieu, nous proposons aussi la pose de fenêtres de toit et la création de pergolas. Pour un travail soigné par un artisan voisin, faites appel à ATB Charpente à Montberon.",
  ],
  "montrabe": [
    "Montrabé, près de 4 500 habitants, est une commune résidentielle de l’est de Toulouse Métropole, à 8 km du centre toulousain et 18 km de notre atelier de Bessières. Bien desservie et appréciée des familles, elle présente un habitat pavillonnaire que votre charpentier couvreur entretient avec régularité.",
    "Sur les pavillons montrabéens, nous traitons la couverture en tuiles terre cuite du Sud-Ouest : remplacement de tuiles cassées, réfection de toiture et démoussage préventif. Les fermettes des lotissements récents sont contrôlées et renforcées au besoin.",
    "La charpente traditionnelle des maisons plus anciennes est restaurée dans les règles, et la zinguerie zinc, gouttières et descentes, garantit une évacuation des eaux fiable. L’isolation de toiture, par l’intérieur ou en sarking, optimise le confort thermique.",
    "Voisine de Beaupuy, Rouffiac-Tolosan et L’Union, Montrabé bénéficie de notre proximité. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente vous accompagne durablement à Montrabé.",
  ],
  "pechbonnieu": [
    "Pechbonnieu, près de 4 900 habitants, fait partie de la CC des Coteaux Bellevue, sur les hauteurs au nord de Toulouse. À 12 km de la ville-centre et seulement 15 km de notre atelier de Bessières, cette commune des coteaux, proche de chez nous, profite de la réactivité de votre charpentier couvreur.",
    "Le relief pechbonnais demande de soigner la charpente bois : nous renforçons les structures exposées et restaurons les charpentes traditionnelles, tout en contrôlant les fermettes des constructions récentes. Le traitement des bois prévient les attaques d’insectes.",
    "La couverture en tuiles canal et romanes, sur ces toits de coteaux, est posée et réfectionnée avec rigueur. La zinguerie zinc, gouttières, noues et descentes, gère efficacement les eaux pluviales, et l’isolation de toiture renforce le confort de l’habitat.",
    "Proches de Gratentour, Castelginest et Montberon, nous proposons aussi la pose de fenêtres de toit et la création de pergolas. Pour un travail soigné par un artisan voisin, choisissez ATB Charpente à Pechbonnieu.",
  ],
  "quint-fonsegrives": [
    "Quint-Fonsegrives, plus de 6 100 habitants, est une commune résidentielle prisée de l’est de Toulouse Métropole, à 8 km du centre toulousain et 25 km de notre atelier de Bessières. Son habitat soigné, fait de belles maisons individuelles, demande à votre charpentier couvreur un travail de grande qualité.",
    "Sur les demeures de Quint-Fonsegrives, nous restaurons les charpentes traditionnelles et contrôlons les fermettes des constructions récentes. Le traitement préventif et curatif des bois protège durablement vos structures de toit contre l’humidité et les insectes.",
    "La couverture en tuiles canal et romanes est réfectionnée et entretenue avec soin, et notre atelier de zinguerie façonne sur mesure gouttières zinc, descentes et habillages. L’isolation de toiture et la pose de fenêtres de toit complètent nos prestations.",
    "Voisine de Flourens, Saint-Orens-de-Gameville et Balma, Quint-Fonsegrives bénéficie de notre savoir-faire. Création de pergola bioclimatique, charpente d’extension, entretien de toiture : ATB Charpente est votre partenaire à Quint-Fonsegrives.",
  ],
  "rabastens": [
    "Rabastens, près de 5 900 habitants, est une cité médiévale du Tarn rattachée à la CA Gaillac-Graulhet, dominant le Tarn avec son église classée au patrimoine de l’UNESCO. À 35 km de Toulouse mais seulement 11 km de notre atelier de Bessières, cette ville d’art mobilise volontiers votre charpentier couvreur.",
    "Le patrimoine rabastinois, riche de demeures anciennes et de bâtisses vigneronnes, recèle de remarquables charpentes traditionnelles. Nous les restaurons avec respect : reprise des fermes et pannes, traitement curatif des bois et remplacement à l’identique des pièces dégradées.",
    "Les toitures rabastinoises en tuiles canal sont réfectionnées, remplacées et démoussées dans le souci de préserver le cachet de la cité. La zinguerie zinc, gouttières, chéneaux et descentes, est façonnée sur mesure pour les bâtiments anciens comme récents.",
    "Proches de Coufouleux, Lisle-sur-Tarn et Grazac, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, attaché au patrimoine tarnais, soigne votre couverture à Rabastens.",
  ],
  "ramonville-saint-agne": [
    "Ramonville-Saint-Agne, plus de 15 100 habitants, est une commune importante du sud de Toulouse, au sein de la CA du Sicoval, réputée pour son port sur le canal du Midi et son pôle technologique. À 7 km du centre toulousain mais 30 km de notre atelier de Bessières, cette ville dynamique présente un bâti varié que votre charpentier couvreur maîtrise.",
    "Sur les maisons ramonvilloises, l’isolation de toiture et l’amélioration énergétique sont souvent au cœur des projets : nous intervenons par l’intérieur ou en sarking, et posons des fenêtres de toit pour valoriser les combles aménagés.",
    "La couverture en tuiles canal et romanes du Sud-Ouest est rénovée, remplacée et démoussée par nos soins. La charpente bois, traditionnelle ou en fermettes, est diagnostiquée et renforcée, et la zinguerie zinc assure gouttières et descentes durables.",
    "Voisine de Labège, Saint-Orens-de-Gameville et Quint-Fonsegrives, Ramonville-Saint-Agne bénéficie de notre savoir-faire complet. Création de pergola, charpente d’extension, entretien de toiture : ATB Charpente vous accompagne à Ramonville-Saint-Agne.",
  ],
  "saint-alban": [
    "Saint-Alban, plus de 6 500 habitants, est une commune résidentielle du nord de Toulouse Métropole, à 10 km du centre toulousain et 19 km de notre atelier de Bessières. Densément peuplée et appréciée des familles, elle offre à votre charpentier couvreur un parc de toitures pavillonnaires à entretenir au fil des ans.",
    "Sur les toits saint-albanais, nous privilégions souvent la couverture : remplacement de tuiles canal ou romanes cassées, réfection de toiture et démoussage. Les fermettes des lotissements récents font l’objet d’un contrôle régulier de notre part.",
    "La charpente traditionnelle des bâtisses anciennes est restaurée dans les règles, et la zinguerie zinc, gouttières et descentes, garantit une évacuation des eaux durable sur ces parcelles parfois resserrées. L’isolation de toiture améliore votre confort thermique.",
    "Limitrophe de Castelginest, Fenouillet et Fonbeauzard, Saint-Alban bénéficie de notre proximité. Pose de fenêtres de toit, création de pergola, entretien annuel : ATB Charpente prend soin de votre couverture à Saint-Alban.",
  ],
  "saint-jean": [
    "Saint-Jean, plus de 11 200 habitants, est une commune dense du nord-est de Toulouse Métropole, à 8 km du centre toulousain et 17 km de notre atelier de Bessières. Son tissu pavillonnaire serré, ponctué de petits collectifs, demande à votre charpentier couvreur rigueur et discrétion.",
    "Dans cet habitat dense, la zinguerie est déterminante : nous façonnons et posons gouttières zinc, descentes et solins pour une évacuation des eaux parfaite, condition indispensable entre parcelles mitoyennes. Noues et habillages sont réalisés avec précision.",
    "La couverture en tuiles canal et romanes est réfectionnée, remplacée et démoussée dans le respect de l’unité des rues. La charpente bois, souvent en fermettes, est diagnostiquée et consolidée, et l’isolation de toiture améliore nettement le confort de l’habitation.",
    "Voisine de Rouffiac-Tolosan, L’Union et Castelmaurou, Saint-Jean bénéficie de notre réactivité. Pose de fenêtres de toit, création de pergola, entretien annuel : confiez votre toiture à un artisan local de confiance à Saint-Jean.",
  ],
  "saint-jory": [
    "Saint-Jory, près de 8 700 habitants, s’étend dans la plaine de la Garonne au nord de Toulouse Métropole, à 17 km du centre toulousain et 21 km de notre atelier de Bessières. Traversée par le canal latéral, cette commune en croissance offre à votre charpentier couvreur des toitures de toutes générations.",
    "Le bâti saint-joryen mêle anciennes maisons de plaine et lotissements récents. Nous restaurons les charpentes traditionnelles et contrôlons les fermettes, avec un traitement systématique des bois contre l’humidité de la plaine et les insectes xylophages.",
    "La couverture en tuiles canal et romanes du Sud-Ouest est posée, rénovée et démoussée par nos soins. La zinguerie zinc, gouttières et descentes, prend ici toute son importance pour évacuer les eaux pluviales, et l’isolation de toiture améliore le confort.",
    "Voisins de Lespinasse, Gagnac-sur-Garonne et Merville, nous installons aussi fenêtres de toit et pergolas. ATB Charpente, artisan local et soigneux, prend en charge tous vos travaux de toiture à Saint-Jory.",
  ],
  "saint-orens-de-gameville": [
    "Saint-Orens-de-Gameville, plus de 14 600 habitants, est une grande commune résidentielle du sud-est de Toulouse Métropole, à 9 km du centre toulousain et 27 km de notre atelier de Bessières. Son habitat soigné, mêlant pavillons et résidences, attend de votre charpentier couvreur un travail à la hauteur.",
    "Sur les demeures saint-orennaises, nous restaurons les charpentes traditionnelles et contrôlons les fermettes des constructions récentes. Le traitement préventif et curatif des bois protège durablement vos structures de toit.",
    "La couverture en tuiles canal et romanes est réfectionnée et entretenue avec soin, et notre atelier de zinguerie façonne sur mesure gouttières zinc, descentes et habillages. L’isolation de toiture et la pose de fenêtres de toit parachèvent nos interventions.",
    "Voisine de Labège, Lauzerville et Quint-Fonsegrives, Saint-Orens-de-Gameville bénéficie de notre savoir-faire. Création de pergola bioclimatique, charpente d’extension, entretien de toiture : ATB Charpente vous accompagne à Saint-Orens-de-Gameville.",
  ],
  "saint-sulpice-la-pointe": [
    "Saint-Sulpice-la-Pointe, près de 9 700 habitants, est une ville en plein essor du Tarn, à la confluence du Tarn et de l’Agout, au sein de la CC Tarn-Agout. À 26 km de Toulouse mais seulement 8 km de notre atelier de Bessières, cette commune toute proche fait de votre charpentier couvreur un véritable voisin.",
    "Cette proximité nous permet d’intervenir très rapidement sur les charpentes bois saint-sulpiciennes : restauration des charpentes traditionnelles des maisons anciennes, contrôle des fermettes et création d’ossatures bois pour vos extensions. Le traitement curatif des bois est l’une de nos forces.",
    "Les toitures locales en tuiles canal sont réfectionnées, remplacées et démoussées avec soin. À la confluence de deux rivières, la zinguerie zinc, gouttières, noues et descentes, est particulièrement importante pour évacuer les eaux pluviales sans risque d’infiltration.",
    "Voisins de Lugan, Azas et Mézens, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. Profitez de la réactivité d’un artisan installé tout près pour vos travaux de toiture à Saint-Sulpice-la-Pointe.",
  ],
  "sainte-foy-d-aigrefeuille": [
    "Sainte-Foy-d’Aigrefeuille, près de 2 600 habitants, est un village des coteaux du Lauragais rattaché à la CC des Terres du Lauragais, au sud-est de Toulouse. À 14 km de la ville-centre et 27 km de notre atelier de Bessières, cette commune verdoyante séduit par ses maisons sur de grands terrains, un cadre familier pour votre charpentier couvreur.",
    "Sur ces coteaux exposés, la couverture est sollicitée par le vent et les intempéries : nous remplaçons les tuiles canal et romanes endommagées et réfectionnons les toitures vieillissantes en respectant le style du Lauragais. Le démoussage prolonge la vie des tuiles.",
    "La charpente bois, traditionnelle dans les bâtisses anciennes ou en fermettes dans les constructions récentes, est diagnostiquée et renforcée. La zinguerie zinc, gouttières, noues et descentes, et l’isolation de toiture complètent chacune de nos interventions.",
    "Proches d’Aigrefeuille, Saint-Pierre-de-Lages et Auzielle, nous posons aussi des fenêtres de toit et créons des pergolas pour profiter des vues du Lauragais. Faites confiance à un artisan local et soigneux pour votre toiture à Sainte-Foy-d’Aigrefeuille.",
  ],
  "seilh": [
    "Seilh, environ 3 350 habitants, s’étire le long de la Garonne au nord-ouest de Toulouse Métropole, à 12 km du centre toulousain et 23 km de notre atelier de Bessières. Réputée pour son golf et son cadre verdoyant, cette commune à taille humaine présente des toitures que votre charpentier couvreur entretient avec attention.",
    "La proximité de la Garonne rend la zinguerie essentielle à Seilh : nous soignons particulièrement gouttières zinc, noues et descentes pour évacuer efficacement les eaux pluviales et prévenir toute humidité. Solins et raccords sont posés avec précision.",
    "La couverture en tuiles canal et romanes du Sud-Ouest fait l’objet de nos réfections, remplacements et démoussages. La charpente bois, traditionnelle ou en fermettes, est diagnostiquée et renforcée, et l’isolation de toiture améliore le confort thermique.",
    "Voisins de Gagnac-sur-Garonne, Aussonne et Fenouillet, nous installons aussi fenêtres de toit et pergolas. Faites confiance à ATB Charpente, artisan local et réactif, pour tous vos travaux de toiture à Seilh.",
  ],
  "verfeil": [
    "Verfeil, près de 4 000 habitants, est un ancien village fortifié de la CC des Coteaux du Girou, à l’est de Toulouse, au caractère médiéval marqué. À 20 km de la ville-centre et seulement 17 km de notre atelier de Bessières, cette commune au beau patrimoine fait régulièrement appel à votre charpentier couvreur.",
    "Le bourg ancien verfeillois abrite de remarquables charpentes traditionnelles que nous restaurons avec rigueur : reprise des fermes, pannes et chevrons, traitement curatif des bois et remplacement à l’identique des pièces dégradées. Les fermettes des maisons récentes sont aussi contrôlées.",
    "Les toitures verfeilloises en tuiles canal et romanes sont réfectionnées, remplacées et démoussées dans le respect du cachet du village. La zinguerie zinc, gouttières et descentes, façonnée sur mesure, sécurise l’évacuation des eaux pluviales.",
    "Proches de Bonrepos-Riquet, Saint-Marcel-Paulel et Gauré, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, respectueux du patrimoine, prend soin de votre couverture à Verfeil.",
  ],
  "villemur-sur-tarn": [
    "Villemur-sur-Tarn, plus de 6 300 habitants, est une ancienne cité fortifiée au bord du Tarn, chef-lieu de la CC Val’Aïgo, au nord-est de Toulouse. À 29 km de la ville-centre mais seulement 11 km de notre atelier de Bessières, cette ville d’histoire est un secteur de prédilection pour votre charpentier couvreur.",
    "Le riche patrimoine villemurien, marqué par sa tour de Défense et ses quais, recèle de superbes charpentes traditionnelles. Nous les restaurons avec respect : reprise des bois de structure, traitement curatif et remplacement à l’identique des éléments fatigués.",
    "Les toitures villemuriennes en tuiles canal, exposées aux crues et aux pluies du Tarn, demandent une zinguerie zinc irréprochable : gouttières, noues et descentes évacuent les eaux pluviales avec efficacité. Réfection de couverture et démoussage complètent nos prestations.",
    "Proches de Villematier, Bondigoux et Villaudric, nous proposons aussi l’isolation de toiture, la pose de fenêtres de toit et la création de pergolas. ATB Charpente, artisan voisin et attaché au patrimoine, soigne votre couverture à Villemur-sur-Tarn.",
  ],
};
